import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import Navigation from "@/components/navigation";
import { Session } from "inspector";
import TestNav from "@/components/test-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <TestNav />
          {/* <Navigation></Navigation> */}
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
