import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "../providers";
import AdminNavigation from "@/components/AdminNavigation";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className={inter.className}>
        <NextAuthProvider>
          <div>
            <Suspense fallback={<Loading />}>
              <AdminNavigation />
              {children}
            </Suspense>
          </div>
        </NextAuthProvider>
      </div>
    </div>
  );
}
